// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nygswvhjncejzjeufsuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55Z3N3dmhqbmNlanpqZXVmc3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTk5NTcsImV4cCI6MjA2MzY5NTk1N30.6JxOTziH4E3n6C2PXIuWJJZpLW8UqXt-UUboR4mplyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);